### ISSUE TITLE
Error when running simspark with ground truth information turned on

### ISSUE THREAD

**Issue by pmacalpine** [klausdorer/magmaChallenge#8]
When I try and run the keepaway challenge with simspark having ground truth information reporting turned on I get what looks to be a parsing error when ground truth information from gazebo is attempted to be extracted.  The following is the error message I see: 

Exception in thread "Thread-19" magma.util.symboltreeparser.IllegalSymbolInputException: Missing brackets in input: (mypos -0.00 -1.00 1.64) (myorien 90.00) (ballpos 0.00 0.00 0.04) (L (pol 1.90 0.30 -60.04) (pol 11.13 0.12 -8.36)) (L (pol 17.39 -59.86 -5.42) (pol 18.67 -53.72 -4.81)) (L (pol 17.42 59.86 -5.34) (pol 18.67 53.49 -5.10)) (L (pol 18.68 -53.78 -4.91) (pol 18.63 53.69 -5.06)) (L (pol 2.80 -60.05 -36.07) (pol 3.18 -36.68 -31.22)) (L (pol 3.18 -36.42 -31.44) (pol 3.39 -12.02 -29.11)) (L (pol 3.40 -11.87 -28.99) (pol 3.39 12.05 -29.17)) (L (pol 3.39 12.05 -29.01) (pol 3.17 36.85 -31.32)) (L (pol 3.17 36.68 -31.18) (pol 2.80 59.89 -36.11)))(HJ (n raj1) (ax 0.00))(HJ (n raj2) (ax 0.00))(HJ (n raj3) (ax -0.00))(HJ (n raj4) (ax -0.00))(HJ (n laj1) (ax 0.00))(HJ (n laj2) (ax -0.00))(HJ (n laj3) (ax -0.00))(HJ (n laj4) (ax -0.00))(HJ (n rlj1) (ax 0.00))(HJ (n rlj2) (ax -0.00))(HJ (n rlj3) (ax -0.00))(HJ (n rlj4) (ax -0.00))(HJ (n rlj5) (ax -0.00))(HJ (n rlj6) (ax 0.00))(HJ (n llj1) (ax 0.00))(HJ (n llj2) (ax 0.00))(HJ (n llj3) (ax -0.00))(HJ (n llj4) (ax -0.00))(HJ (n llj5) (ax -0.00))(HJ (n llj6) (ax -0.00))
    at magma.util.symboltreeparser.SymbolTreeParser.parseReal(SymbolTreeParser.java:161)
    at magma.util.symboltreeparser.SymbolTreeParser.parse(SymbolTreeParser.java:54)
    at magma.tools.benchmark.model.proxy.BenchmarkAgentProxy.extractGazeboGroundTruth(BenchmarkAgentProxy.java:158)
    at magma.tools.benchmark.model.proxy.BenchmarkAgentProxy.onNewServerMessage(BenchmarkAgentProxy.java:108)
    at magma.tools.SAProxy.impl.AgentProxy$ServerPerceptionsForwarder.run(AgentProxy.java:228)

**Comment by Gama11** [comment]
Hm, I guess it makes sense that that happens. Probably need an isGazebo check there.
